#
# Copyright 2009 Nexell Co.
#
# Makefile for the SLsi CPU

obj-$(CONFIG_USB_NXP) += setup-usb-phy.o
obj-$(CONFIG_USB_DWCOTG) += setup-usb-dwcotg.o
obj-$(CONFIG_USB_CONNECT_NXP_DRV)   += usb-connector.o
